- name: User tasks
  ansible.builtin.include_tasks:
    file: 'user.yml'
    apply:
      tags: sorryserver.user
  tags: sorryserver.user

- name: SSH tasks
  ansible.builtin.include_tasks:
    file: 'ssh.yml'
    apply:
      tags: sorryserver.ssh
  tags: sorryserver.ssh

- name: Python tasks
  ansible.builtin.include_tasks:
    file: 'python.yml'
    apply:
      tags: sorryserver.python
  tags: sorryserver.python

- name: Nginx tasks
  ansible.builtin.include_tasks:
    file: 'nginx.yml'
    apply:
      tags: sorryserver.nginx
  tags: sorryserver.nginx
