- name: Install nginx
  ansible.builtin.package:
    name: nginx

- name: Ensure nginx is running
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true

- name: Add base nginx configuration file
  ansible.builtin.copy:
    dest: /etc/nginx/nginx.conf
    src: '{{ nginx_config_path }}'
    owner: root
    group: root
    mode: '0644'
  notify: Reload nginx

- name: Create vhosts directory
  ansible.builtin.file:
    path: /var/www/vhosts/
    state: directory
    mode: '0755'
    owner: kis
    group: kis

- name: Set SELinux permission
  community.general.sefcontext:
    target: '/var/www/vhosts(/.*)?'
    setype: httpd_sys_content_t
    reload: true
    state: present
  register: filecontext

- name: Run restore context to reload selinux
  ansible.builtin.command: restorecon -R -v /var/www/vhosts/
  changed_when: filecontext.changed
