- name: Install nginx
  ansible.builtin.package:
    name: nginx

- name: Ensure nginx is running
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true

- name: Add base nginx configuration file
  ansible.builtin.copy:
    dest: /etc/nginx/nginx.conf
    src: '{{ nginx_config_path }}'
    owner: root
    group: root
    mode: '0644'
  notify: Reload nginx
